### ISSUE TITLE
Block dans Eastern Palace qui se pousse 2 fois et bloque l'entrée de la porte

### ISSUE THREAD

**Issue by KaKaShUruKioRa** [KaKaShUruKioRa/A-Link-to-the-Past-Project#20]
Un Block dans Eastern Palace qui se pousse 2 fois et bloque l'entrée de la porte (et Escalier).

Un Block n'a pas d'AutoBlock, mais ne devrait juste pas être poussable

![image](https://github.com/KaKaShUruKioRa/A-Link-to-the-Past-Project/assets/69737302/17a951be-13bb-43c9-80ac-ed0ce380e8c9)

**Comment by ZeldoRetro** [comment]
Corrigé.
